project_id = "cynnbynmicfosozmgjua"

[functions.check-services]
verify_jwt = false

[functions.integration-oauth]
verify_jwt = false

[functions.integration-oauth-callback]
verify_jwt = false

[functions.integration-sync]
verify_jwt = false

[functions.waitlist-welcome]
verify_jwt = false
